-- AlterTable
ALTER TABLE "site_config" ADD COLUMN     "about_awards" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN     "about_bio" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "about_galleries" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN     "about_media" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN     "about_memberships" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN     "about_name" TEXT,
ADD COLUMN     "about_shows" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN     "about_stat_image1_url" TEXT,
ADD COLUMN     "about_stat_image2_url" TEXT,
ADD COLUMN     "about_statement" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "blog_enabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "contact_email" TEXT,
ADD COLUMN     "contact_phone" TEXT,
ADD COLUMN     "meta_description" TEXT,
ADD COLUMN     "newsletter_tagline" TEXT,
ADD COLUMN     "newsletter_title" TEXT,
ADD COLUMN     "og_image_url" TEXT,
ADD COLUMN     "profile_full_res_url" TEXT,
ADD COLUMN     "profile_image_url" TEXT,
ADD COLUMN     "profile_thumb_url" TEXT,
ADD COLUMN     "studio_image_url" TEXT,
ADD COLUMN     "studio_location" TEXT,
ADD COLUMN     "timezone" TEXT;
